name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
    paths-ignore:
      - '.github/workflows/**'
      - '.github/release_drafter.yml'
      - 'README.md'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'images/**'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install pyinstaller click kubernetes tabulate
      - name: Build binary
        run: |
          pyinstaller --onefile --name kiss app/main.py
      - name: Archive binary (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          tar -czvf kiss_${{ github.ref_name }}_${{ runner.os }}.tar.gz -C dist kiss
      - name: Archive binary (Windows)
        if: runner.os == 'Windows'
        run: |
          Compress-Archive -Path dist\kiss.exe -DestinationPath kiss_${{ github.ref_name }}_windows.zip
      - name: Generate checksums
        run: |
          for file in kiss_${{ github.ref_name }}_*; do
            if [[ -f "$file" ]]; then
              shasum -a 256 "$file" > "$file.sha256"
            fi
          done
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kiss-${{ runner.os }}
          path: |
            kiss_${{ github.ref_name }}_*.tar.gz
            kiss_${{ github.ref_name }}_*.zip
            kiss_${{ github.ref_name }}_*.sha256

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./dist
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/**/*
          draft: false
          generate_release_notes: true